### ISSUE TITLE
Migrate services from rock64

### ISSUE THREAD

**Issue by axeII** [axeII/home-ops#569]
It's time to depreciate rock64. He served well over the years. 

Rock64 deserves honorable discharge. 🫡

## todo
That means I'll need to migrate the services and distribute them:
* [x] tailscale ->k8s/helm
* [x] pihole -> nextdns
* [x] nginx proxy -> traefik k8s
* [x] metube -> helm k8s
* [x] ubooquity -> kavita k8s
* [x] transmission -> deluge k8s
* [x] status -> eunomia or cloud. Blocked by https://github.com/axeII/home-ops/issues/593 

## Other actions
* [x] This will also require repair k8s-gateway.  Fixed by: https://github.com/axeII/home-ops/issues/567
